# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bocker < Formula
  desc "Bocker is a command line tool which creates a backup from a PostgreSQL database,
wraps it in a Docker image, and uploads it to Docker Hub.
Of course, Bocker will also do the reverse and restore your database from a backup in Docker Hub.
"
  homepage "https://github.com/bueti/bocker"
  version "0.8.3"
  license "MIT"

  depends_on "docker"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bueti/bocker/releases/download/v0.8.3/bocker_0.8.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "289568a1c1e1b2061462710639a478181e91d5ef61d598a100a2358f2b5b58a4"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.3/bocker_0.8.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c7c0cb9db2bdc5143a70faa66472c8ee82cb85b422ed05e5d5a471106d527c48"

      def install
        bin.install "bocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bueti/bocker/releases/download/v0.8.3/bocker_0.8.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4740e48ecbb79eab5cc6955f9a9b4c16b3564a3893830647cfdcaee0b70b53ae"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.3/bocker_0.8.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab766c2ec118210e32fea2e01ccd41a240942de6911ca3bfa074f2c471d02569"

      def install
        bin.install "bocker"
      end
    end
  end
end
