# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bocker < Formula
  desc "Bocker is a command line tool which creates a backup from a PostgreSQL database,
wraps it in a Docker image, and uploads it to Docker Hub.
Of course, Bocker will also do the reverse and restore your database from a backup in Docker Hub.
"
  homepage "https://github.com/bueti/bocker"
  version "0.8.2"
  license "MIT"

  depends_on "docker"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bueti/bocker/releases/download/v0.8.2/bocker_0.8.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4cc0e63b30ee3886ffb4f40583994605620b3658f74bcb895d29c62d8f20f172"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.2/bocker_0.8.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "27a575867945cea53f7f73898187104f19d32559f84f2846e3c5e6773a36a2dc"

      def install
        bin.install "bocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.2/bocker_0.8.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "9735c3e283a9863a227a1a903a9f712f73d625faba19d60bdc3bedfd9e5f3965"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bueti/bocker/releases/download/v0.8.2/bocker_0.8.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1fe973bc8d81846bdcec4c00e6cb3b8d7b906437df0095aba6facfc0351bd4a6"

      def install
        bin.install "bocker"
      end
    end
  end
end
