# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bocker < Formula
  desc "Bocker is a command line tool which creates a backup from a PostgreSQL database,
wraps it in a Docker image, and uploads it to Docker Hub.
Of course, Bocker will also do the reverse and restore your database from a backup in Docker Hub.
"
  homepage "https://github.com/bueti/bocker"
  version "0.8.0"
  license "MIT"

  depends_on "docker"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bueti/bocker/releases/download/v0.8.0/bocker_0.8.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ee5ec444dac36b9e8dd32d8bfb798b7c019debb41c5d23720cf54a49aec778b5"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.0/bocker_0.8.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0243c1a6f9ccf854344247bec31115965ec67e41f18c04fbf77f8db696f2e9a2"

      def install
        bin.install "bocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bueti/bocker/releases/download/v0.8.0/bocker_0.8.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ca9a2ea7244a4169eede02fa2f9e00bfb72ead48eaa28d6fe9f870fad3001d13"

      def install
        bin.install "bocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bueti/bocker/releases/download/v0.8.0/bocker_0.8.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0392e83fc5239d50534b0c1c29dda7d5bf0458318f138787648f403ede98886e"

      def install
        bin.install "bocker"
      end
    end
  end
end
