# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrink < Formula
  desc "Bocker is a command line tool which creates a backup from a PostgreSQL database,
wraps it in a Docker image, and uploads it to Docker Hub.
Of course, Bocker will also do the reverse and restore your database from a backup in Docker Hub.
"
  homepage "https://shrink.ch"
  version "0.1.0"
  license "MIT"

  depends_on "docker"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bueti/shrinkster/releases/download/v0.1.0/shrinkster_0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "73ef90fc992fddd9d29e27738e5157090b93f61442ccfbdb497eb9eaec505186"

      def install
        bin.install "shrink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bueti/shrinkster/releases/download/v0.1.0/shrinkster_0.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d715cba1a4f63ac63ced417235cce9b6acaf1d0a6f8680251c96eba5bcc0c9a9"

      def install
        bin.install "shrink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bueti/shrinkster/releases/download/v0.1.0/shrinkster_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "62e6110baf8bd06b6d0a972e0a584c0e49940ed7c8d21c7441da85f519dc08db"

      def install
        bin.install "shrink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bueti/shrinkster/releases/download/v0.1.0/shrinkster_0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d7f1f5daf8c0ff0ae92ca54834989f4bb8ad686e6eb6ce8b1d7b10a43887bd67"

      def install
        bin.install "shrink"
      end
    end
  end
end
